### ISSUE TITLE
[Bug]: Captcha throws a token failure error when submitting a form more than once, without refreshing the page

### ISSUE THREAD

**Issue by iDiegoNL** [coderflexx/laravel-turnstile#5]
### What happened?

The captcha throws a token failure error when submitting a form more than once, without refreshing the page.

### How to reproduce the bug

Steps to reproduce:
- Fill in a form and make sure that another validation fails, while letting the captcha pass
- Submit the form
- It will return the other validation message (expected behavior)
- Now submit the form again, it does not matter whether you let the other validation pass or fail.
- Turnstile will now throw the `turnstile_check_message` validation error, presumably because it's trying to re-use a token while they're [single-use](https://developers.cloudflare.com/turnstile/frequently-asked-questions/#can-a-turnstile-token-be-used-twice).

![Untitled](https://github.com/coderflexx/laravel-turnstile/assets/10339564/53287150-2769-4256-8cf3-f8fb77e574ab)

### Package Version

1.0.4

### PHP Version

8.1

### Laravel Version

10.13.1

**Comment by ousid** [comment]
Hi, @iDiegoNL 

Can you share the backend responsible for the form above? To demonstrate the issue, and have a solution quickly.

**Comment by iDiegoNL** [comment]
@ousid I have created a repository to showcase the code and issue here: https://github.com/iDiegoNL/coderflexx-laravel-turnstile-livewire-bug-example/blob/master/app/Http/Livewire/ExamplePage.php

To reproduce the issue on the example repo, simply press the "Submit" button twice.

However, I am not sure if this issue belongs in this repo, or in the coderflexx/filament-turnstile repo.
Please do let me know if you need any other information!

**Comment by ousid** [comment]
@iDiegoNL I see you are using __filament form__, package.

Have you tried the [filament package](https://github.com/coderflexx/filament-turnstile)?

**Comment by iDiegoNL** [comment]
> @iDiegoNL I see you are using __filament form__, package.
> 
> 
> 
> Have you tried the [filament package](https://github.com/coderflexx/filament-turnstile)?

Yes, this issue happens with your filament package as well (see the composer.json file in the example repo that I linked) :). Therefore, i am not sure if this issue belongs in this repo, or in the other.

**Comment by ousid** [comment]
@iDiegoNL, yeah. That's odd.

Maybe a quick solution for now, is to have an `emit` event, if is a validation error, you'll refresh the captcha token. Not sure atm on how it will be done exactly. But I'll look into it later this weekend.

PS: if you have any suggestion on how to be done, or an Idea. I'll be happy to hear them out.

**Comment by ousid** [comment]
Fixed in https://github.com/coderflexx/filament-turnstile/pull/12
